
title: My Portfolio

author:
  name: F White

description: Scientific visualization

header_pages:
  - Posters.md
  
url: https://whitef19.github.io

# Build settings
theme: jekyll-theme-cayman
future: true
